In [1]:
import numpy as np

In [5]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
np.ones((2, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [81]:
np.random.seed(10)
np.random.random((3, 4))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335]])

In [66]:
np.random.seed(1)
np.random.randint(10, 20, size=(4,5))

array([[15, 18, 19, 15, 10],
       [10, 11, 17, 16, 19],
       [12, 14, 15, 12, 14],
       [12, 14, 17, 17, 19]])

In [74]:
# Seed value is generated automatically
np.random.uniform(10.0, 50.0, size=(4,5))

array([[24.84535604, 12.00072344, 39.63822223, 21.94720968, 18.17432511],
       [49.27026565, 45.72084849, 40.3739518 , 36.04482236, 11.58734008],
       [42.55505461, 40.50292539, 28.21129868, 31.27305805, 14.3734427 ],
       [15.84130984, 30.35154955, 18.62601124, 46.65774812, 28.48610051]])