In [1]:
import numpy as np

In [5]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [6]:
np.arange(10, 15)

array([10, 11, 12, 13, 14])

In [4]:
np.arange(2, 10, 3)

array([2, 5, 8])

In [15]:
np.arange(-15, 5, 4)

array([-15, -11,  -7,  -3,   1])

In [7]:
np.arange(20).reshape([2, 10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [9]:
np.arange(20).reshape([4, 5])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
np.arange(20).reshape([2, 2, 5])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [13]:
np.array([10, 2, 5, 7, 9, 15, 25, 30, 35, 40]).reshape([2, 5])

array([[10,  2,  5,  7,  9],
       [15, 25, 30, 35, 40]])

In [18]:
np.array([10, 2, 5, 7, 9, 15, 25, 30, 35, 40]).reshape([2, 5]).reshape([10, 1])

array([[10],
       [ 2],
       [ 5],
       [ 7],
       [ 9],
       [15],
       [25],
       [30],
       [35],
       [40]])

In [22]:
np.random.random((4, 3, 3)).flatten()

array([0.85194423, 0.54984096, 0.62325161, 0.51418508, 0.19403962,
       0.43505885, 0.93779544, 0.40903673, 0.08789108, 0.99974998,
       0.54030725, 0.34959375, 0.72158741, 0.04998791, 0.487174  ,
       0.50100827, 0.5277219 , 0.76122315, 0.44504901, 0.27403076,
       0.51285503, 0.26753307, 0.15365041, 0.94592239, 0.00528848,
       0.70687001, 0.85054936, 0.60573892, 0.51811623, 0.91354745,
       0.98023079, 0.12017769, 0.13071763, 0.67694419, 0.58325113,
       0.85453665])

In [14]:
np.array([10, 2, 5, 7, 9, 15, 25, 30, 35, 40]).reshape([3, 5])

ValueError: cannot reshape array of size 10 into shape (3,5)